// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApMTQmhKwsK3nHcedjBK7Jczl3xMzMm-s',
    appId: '1:402166224390:web:bc3fa8dc8d3ee02c7c1587',
    messagingSenderId: '402166224390',
    projectId: 'chat-app-f45d9',
    authDomain: 'chat-app-f45d9.firebaseapp.com',
    storageBucket: 'chat-app-f45d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-9kvDQe0qhG7uNDZlRy5TjMtRRP6Ege0',
    appId: '1:402166224390:android:2e3fdb79405fd7c47c1587',
    messagingSenderId: '402166224390',
    projectId: 'chat-app-f45d9',
    storageBucket: 'chat-app-f45d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPYf1kYbrpktDH2rhfqKxdSAwWYNhQomI',
    appId: '1:402166224390:ios:882cde25022913a47c1587',
    messagingSenderId: '402166224390',
    projectId: 'chat-app-f45d9',
    storageBucket: 'chat-app-f45d9.appspot.com',
    iosClientId: '402166224390-6d5ru0ib0ckouvmvs4kktp06c7q226c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPYf1kYbrpktDH2rhfqKxdSAwWYNhQomI',
    appId: '1:402166224390:ios:882cde25022913a47c1587',
    messagingSenderId: '402166224390',
    projectId: 'chat-app-f45d9',
    storageBucket: 'chat-app-f45d9.appspot.com',
    iosClientId: '402166224390-6d5ru0ib0ckouvmvs4kktp06c7q226c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
